### ISSUE TITLE
Any thoughts re: XanMod Kernel (preempt RT with many RT settings active)

### ISSUE THREAD

**Issue by juwalter** [icshwi/etherlabmaster#11]
Thanks for sharing this project - great work!!

Quick question: do you know about/tried/plans for https://xanmod.org/

from their website:

-  Preemptive Full **Tickless Kernel at 500Hz** w/ Tuned CPU Core Scheduler.
- Caching, Virtual Memory Manager and CPU Governor improvements.
- RCU Boost for better multitasking and lower DRI frametime latency in Games and Production Applications.
- Generic kernel package for compatibility with most Debian & Ubuntu based distributions. Built on the latest GCC 9.2 and Binutils 2.33.

Sadly, it seems only "Real-time Linux kernel (PREEMPT_RT) build available [5.4-rt] [4.19-rt]" which would mean, that Gavins patchset wont work (up to 4.4 only?)

Best, Jürgen

**Comment by jeonghanlee** [comment]
We limited our resources to Debian, CentOS, and our own Linux distribution.  BTW, you can look at our own RT kernel configuration in the following site: https://github.com/icshwi/realtime-config

The above preempt RT configuration meets our current requirements well.

**Comment by juwalter** [comment]
fantastic - thanks for the quick reply!
