### ISSUE TITLE
E3_ETHERLAB_CONF_OPTIONS is unavailable for non-generic devices.

### ISSUE THREAD

**Issue by hallychou** [icshwi/etherlabmaster#4]
In CONFIG_MODULE
```
# 
E3_ETHERLAB_CONF_OPTIONS:=--disable-8139too
#
E3_ETHERLAB_CONF_OPTIONS+=--enable-igb
#
E3_ETHERLAB_CONF_OPTIONS+=--enable-sii-assign=yes
#
E3_ETHERLAB_CONF_OPTIONS+=--enable-eoe=no
```
When make dkms_build, an error is returned.

> ERROR (dkms apport): binary package for etherlabmaster: 1.5.2 not found
> Error!  Build of devices/ec_generic.ko failed for: 4.4.138-rt155 (i686)
> Consult the make.log in the build directory
> /var/lib/dkms/etherlabmaster/1.5.2/build/ for more information.
> etherlabmaster.Makefile:56: recipe for target 'dkms_build' failed
> make[1]: *** [dkms_build] Error 7
> make[1]: Leaving directory '/home/jk/etherlabmaster/etherlabmaster-code'
> /home/jk/etherlabmaster/configure/E3/RULES_ETHERLAB:86: recipe for target 'dkms_build' failed
> make: *** [dkms_build] Error 2

Only enable-generic is OK.

**Comment by jeonghanlee** [comment]
This repository is only tested with the Debian & CentOS with also only the Generic EtherCAT Device Driver. So it may need to change a lot of files  in order to use other device drivers. And please be aware the revision I am using in this repo also,  9e65f7 in the main repository of the etherlab master without any source codes patch files.  Since then, a bit more commits you may find in.

**Comment by jeonghanlee** [comment]
Options are available now, but the dkms configuration is not.

**Comment by jeonghanlee** [comment]
By using the following commands, one can check the options easily. 
`make showopts`
And the options can be defined in the `configure/CONFIG_OPTIONS` and its corresponding `.local` file. 
I can switch between `generic` and `e1000e` with this method. Please give your try and let me know. 
Currently, I don't know which is better to build `ethercat.conf` file automatically. So please use only `one master`.
