### ISSUE TITLE
systemctl start ethercat error

### ISSUE THREAD

**Issue by hallychou** [icshwi/etherlabmaster#5]
setup by default configuration, everything seems right
but systemctl start ethercat
> Job for ethercat.service failed because the control process exited with error code. See "systemctl status ethercat.service" and "journalctl -xe" for details.

and systemctl status ethercat.service

> ● ethercat.service - EtherCAT Master Kernel Modules
>    Loaded: loaded (/etc/systemd/system/ethercat.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since 2018-11-10 16:33:34 CST; 8s ago
>   Process: 1842 ExecStart=/opt/etherlab/sbin/ethercatctl start (code=exited, status=1/FAILURE)
>  Main PID: 1842 (code=exited, status=1/FAILURE)
> 
> 11 10 16:33:34 jktech systemd[1]: Starting EtherCAT Master Kernel Modules...
> 11 10 16:33:34 jktech ethercatctl[1842]: modprobe: ERROR: could not insert 'ec_master': Unknown symbol in module, or unknown parameter (see dmesg)
> 11 10 16:33:34 jktech systemd[1]: ethercat.service: Main process exited, code=exited, status=1/FAILURE
> 11 10 16:33:34 jktech systemd[1]: Failed to start EtherCAT Master Kernel Modules.
> 11 10 16:33:34 jktech systemd[1]: ethercat.service: Unit entered failed state.
> 11 10 16:33:34 jktech systemd[1]: ethercat.service: Failed with result 'exit-code'.
>

**Comment by hallychou** [comment]
and after dmesg, I found

> [    8.085416] ec_master: loading out-of-tree module taints kernel.
> [    8.085588] ec_master: module verification failed: signature and/or required key missing - tainting kernel
> [    8.085657] ec_master: Unknown symbol __x86_indirect_thunk_edx (err 0)
> [    8.085670] ec_master: Unknown symbol __x86_indirect_thunk_ecx (err 0)
> [    8.085687] ec_master: Unknown symbol __x86_indirect_thunk_edi (err 0)
> [    8.085722] ec_master: Unknown symbol __x86_indirect_thunk_eax (err 0)

**Comment by jeonghanlee** [comment]
The systemd starts the ethercat.service properly, but the compiled kernel module is not right.  Please see https://github.com/icshwi/etherlabmaster/issues/4#issuecomment-437626866 

I will close this issue soon, because the error isn't related with the functional systemd service.
